# AWS: PV and PVC at the Shared level
{{- if not .Values.storage.existingClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opcenter-metadata-pvc-{{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: opcenter-metadata-pv
{{- end }}
