{{- if .Values.Fsx.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: opcfsxsecrets
type: Opaque
data:
  {{- if .Values.Fsx.createSecret}}
  domain: {{ .Values.Fsx.domain | b64enc }}
  password: {{ .Values.Fsx.password | b64enc }}
  username: {{ .Values.Fsx.username | b64enc }}
  {{- end }} 
{{- end }}